import type { DashboardSummary, Notification, Topology } from "./api";

/** Seeded demo payload — mirrors packages/database/prisma/seed.ts for offline UI. */
export const DEMO_DASHBOARD: DashboardSummary = {
  inventoryMeters: [
    {
      code: "FOSTER_CREEK",
      name: "Foster Creek",
      bitumenBbls: 485_000,
      diluentBbls: 142_000,
      totalStorageCapacityBbls: 750_000,
      storageUtilizationPct: 84,
      status: "restricted",
    },
    {
      code: "CHRISTINA_LAKE",
      name: "Christina Lake",
      bitumenBbls: 520_000,
      diluentBbls: 98_000,
      totalStorageCapacityBbls: 800_000,
      storageUtilizationPct: 77,
      status: "optimal",
    },
    {
      code: "SUNRISE",
      name: "Sunrise",
      bitumenBbls: 310_000,
      diluentBbls: 45_000,
      totalStorageCapacityBbls: 500_000,
      storageUtilizationPct: 71,
      status: "optimal",
    },
    {
      code: "LLOYD_UPGRADER",
      name: "Lloydminster Upgrader",
      bitumenBbls: 380_000,
      diluentBbls: 95_000,
      totalStorageCapacityBbls: 1_200_000,
      storageUtilizationPct: 40,
      status: "optimal",
    },
  ],
  pipelineMatrix: [
    {
      code: "PL-FC-LH",
      name: "Foster Creek → Lloyd Hub",
      source: "Foster Creek",
      destination: "Lloydminster Gathering Hub",
      status: "ACTIVE",
      utilizationRatePct: 83,
      maxDailyCapacityBbls: 200_000,
      currentFlowBblsPerDay: 165_000,
    },
    {
      code: "PL-CL-LH",
      name: "Christina Lake → Lloyd Hub",
      source: "Christina Lake",
      destination: "Lloydminster Gathering Hub",
      status: "ACTIVE",
      utilizationRatePct: 85,
      maxDailyCapacityBbls: 220_000,
      currentFlowBblsPerDay: 188_000,
    },
    {
      code: "PL-SR-LH",
      name: "Sunrise → Lloyd Hub",
      source: "Sunrise",
      destination: "Lloydminster Gathering Hub",
      status: "RESTRICTED",
      utilizationRatePct: 80,
      maxDailyCapacityBbls: 140_000,
      currentFlowBblsPerDay: 112_000,
    },
    {
      code: "PL-LH-UP",
      name: "Lloyd Hub → Upgrader",
      source: "Lloydminster Gathering Hub",
      destination: "Lloydminster Upgrader",
      status: "ACTIVE",
      utilizationRatePct: 85,
      maxDailyCapacityBbls: 350_000,
      currentFlowBblsPerDay: 298_000,
    },
    {
      code: "PL-LH-HT",
      name: "Lloyd Hub → Hardisty Terminal",
      source: "Lloydminster Gathering Hub",
      destination: "Hardisty Terminal",
      status: "ACTIVE",
      utilizationRatePct: 53,
      maxDailyCapacityBbls: 180_000,
      currentFlowBblsPerDay: 95_000,
    },
    {
      code: "PL-HT-RF",
      name: "Hardisty → Eastern Refinery",
      source: "Hardisty Terminal",
      destination: "Eastern Refinery Complex",
      status: "ACTIVE",
      utilizationRatePct: 45,
      maxDailyCapacityBbls: 160_000,
      currentFlowBblsPerDay: 72_000,
    },
  ],
  kpis: {
    activeShipments: 4,
    openIncidents: 0,
    unreadNotifications: 2,
    inventoryWarnings: 1,
    pendingApprovals: 1,
    scadaTagCount: 12,
  },
};

export const DEMO_NOTIFICATIONS: Notification[] = [
  {
    id: "demo-1",
    title: "Diluent inventory below threshold",
    message: "Sunrise facility diluent below 15% of storage — review blend schedule.",
    severity: "WARNING",
    isRead: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-2",
    title: "Pipeline PL-SR-LH restricted",
    message: "Sunrise → Lloyd Hub operating at reduced capacity pending maintenance window.",
    severity: "HIGH_PRIORITY",
    isRead: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-3",
    title: "Blend batch scheduled",
    message: "Commercial scheduler approved Foster Creek 40k bbl blend at 28% diluent ratio.",
    severity: "INFO",
    isRead: true,
    createdAt: new Date().toISOString(),
  },
];

export const DEMO_TOPOLOGY: Topology = {
  nodes: [
    { id: "fc", code: "FOSTER_CREEK", name: "Foster Creek", type: "PRODUCTION_ASSET" },
    { id: "cl", code: "CHRISTINA_LAKE", name: "Christina Lake", type: "PRODUCTION_ASSET" },
    { id: "sr", code: "SUNRISE", name: "Sunrise", type: "PRODUCTION_ASSET" },
    { id: "lh", code: "LLOYD_HUB", name: "Lloydminster Gathering Hub", type: "MIDSTREAM_HUB" },
    { id: "up", code: "LLOYD_UPGRADER", name: "Lloydminster Upgrader", type: "UPGRADER" },
    { id: "ht", code: "HARDISTY_TERMINAL", name: "Hardisty Terminal", type: "TERMINAL" },
    { id: "rf", code: "REFINERY_EAST", name: "Eastern Refinery Complex", type: "REFINERY" },
  ],
  edges: [
    { id: "e1", code: "PL-FC-LH", source: "fc", target: "lh", status: "ACTIVE", maxDailyCapacityBbls: 200_000 },
    { id: "e2", code: "PL-CL-LH", source: "cl", target: "lh", status: "ACTIVE", maxDailyCapacityBbls: 220_000 },
    { id: "e3", code: "PL-SR-LH", source: "sr", target: "lh", status: "RESTRICTED", maxDailyCapacityBbls: 140_000 },
    { id: "e4", code: "PL-LH-UP", source: "lh", target: "up", status: "ACTIVE", maxDailyCapacityBbls: 350_000 },
    { id: "e5", code: "PL-LH-HT", source: "lh", target: "ht", status: "ACTIVE", maxDailyCapacityBbls: 180_000 },
    { id: "e6", code: "PL-HT-RF", source: "ht", target: "rf", status: "ACTIVE", maxDailyCapacityBbls: 160_000 },
  ],
  adjacency: [
    { primary: "PL-CL-LH", alternate: "PL-CL-HT", additionalDelayDays: 2, priority: 1 },
    { primary: "PL-SR-LH", alternate: "PL-FC-LH", additionalDelayDays: 3, priority: 2 },
  ],
};
